version: '3'

services:
    unblockneteasemusic:
        build: .
        env_file: .env
        environment:
            NODE_ENV: production

        # Change sources here
        command: ["-o", "bilibili", "kugou", "kuwo", "ytdlp", "bodian","youtube", "youtubedl", "bilivideo", "pyncmd"]

        ports:
            - ${HTTP_PROXY_PORT:-58080}:8080
            - ${HTTPS_PROXY_PORT:-58081}:8081